# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY.
_commit: c0d2a49
_src_path: git@github.com:josephcourtney/skellington.git
cli_smoke: ""
line_length: 120
project_name: wordrobe
python_min: "3.14"
python_package: true
